################################################################################
# "Copyright (C) 2013, ApS s.r.o Brno, All Rights Reserved"
#  Generated by Codasip HW generator v2.0.0
#  date: Mon Mar  4 12:01:29 2013
#  brief: Start shell script.
################################################################################


#!/bin/bash

# Change path if necessary
#export PATH=$PATH:
# License file
#export LM_LICENSE_FILE=

cd /home/ipodivinsky/funi/haven/combov2/top/combov2/designs

csboot -f 0 robot_hloupy.mcs

cd /home/ipodivinsky/funi/haven/libsze_wrapper

./libsze_read
